# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddingUsers():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addingUsers(self):
    # Test name: Adding Users
    # Step # | name | target | value
    # 1 | open | https://admin.tez.io/workspaces/65d66fb458521dc38ff84bb5?tab=Users | 
    self.driver.get("https://admin.tez.io/workspaces/65d66fb458521dc38ff84bb5?tab=Users")
    # 2 | setWindowSize | 2576x1407 | 
    self.driver.set_window_size(2576, 1407)
    # 3 | click | css=.-right-2 | 
    self.driver.find_element(By.CSS_SELECTOR, ".-right-2").click()
    # 4 | mouseOver | css=.-right-2 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".-right-2")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | css=.stroke-highlightColor | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | click | css=.hover\3A cursor-pointer | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A cursor-pointer").click()
    # 7 | click | css=.relative:nth-child(2) > .relative > #search | 
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) > .relative > #search").click()
    # 8 | type | css=.relative:nth-child(2) > .relative > #search | Craig
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) > .relative > #search").send_keys("Craig")
    # 9 | click | xpath=(//input[@type='checkbox'])[6] | 
    self.driver.find_element(By.XPATH, "(//input[@type=\'checkbox\'])[6]").click()
    # 10 | click | css=#headlessui-dialog-panel-51 > .justify-between | 
    self.driver.find_element(By.CSS_SELECTOR, "#headlessui-dialog-panel-51 > .justify-between").click()
    # 11 | click | css=#headlessui-dialog-title-38 > .text-gray-400 | 
    self.driver.find_element(By.CSS_SELECTOR, "#headlessui-dialog-title-38 > .text-gray-400").click()
    # 12 | click | css=.relative:nth-child(2) > .relative > #search | 
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) > .relative > #search").click()
    # 13 | click | css=div:nth-child(4) > .cursor-pointer > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .cursor-pointer > .flex").click()
    # 14 | click | css=#headlessui-dialog-title-38 > .text-gray-400 | 
    self.driver.find_element(By.CSS_SELECTOR, "#headlessui-dialog-title-38 > .text-gray-400").click()
    # 15 | click | xpath=//h3[@id='headlessui-dialog-title-38']/span | 
    self.driver.find_element(By.XPATH, "//h3[@id=\'headlessui-dialog-title-38\']/span").click()
    # 16 | click | xpath=//div[@id='headlessui-dialog-panel-47']/div | 
    self.driver.find_element(By.XPATH, "//div[@id=\'headlessui-dialog-panel-47\']/div").click()
    # 17 | click | xpath=//button[contains(.,'Submit')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Submit\')]").click()
    # 18 | click | css=.-right-2 | 
    self.driver.find_element(By.CSS_SELECTOR, ".-right-2").click()
    # 19 | click | css=.hover\3A cursor-pointer | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A cursor-pointer").click()
    # 20 | click | css=.relative:nth-child(2) > .relative > #search | 
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) > .relative > #search").click()
  
