# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSettings():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_settings(self):
    # Test name: settings
    # Step # | name | target | value
    # 1 | open | https://admin.tez.io/workspaces/65d79f5558521dc38ff870ea | 
    self.driver.get("https://admin.tez.io/workspaces/65d79f5558521dc38ff870ea")
    # 2 | setWindowSize | 1536x814 | 
    self.driver.set_window_size(1536, 814)
    # 3 | click | xpath=//span[contains(.,'Settings')] | 
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Settings\')]").click()
    # 4 | click | css=.relative:nth-child(2) > .w-full > .group .absolute | 
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) > .w-full > .group .absolute").click()
    # 5 | click | name=column-name | 
    # txt corporation.name
    self.driver.find_element(By.NAME, "column-name").click()
    # 6 | click | css=.min-h-\[17\.5px\] | 
    self.driver.find_element(By.CSS_SELECTOR, ".min-h-\\[17\\.5px\\]").click()
    # 7 | click | xpath=//span/div | 
    self.driver.find_element(By.XPATH, "//span/div").click()
    # 8 | click | name=column-value | 
    # Text Value
    self.driver.find_element(By.NAME, "column-value").click()
    # 9 | click | name=column-value | 
    self.driver.find_element(By.NAME, "column-value").click()
    # 10 | type | name=column-value | CustomerName
    self.driver.find_element(By.NAME, "column-value").send_keys("CustomerName")
    # 11 | sendKeys | name=column-value | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "column-value").send_keys(Keys.ENTER)
  
